# Generated by Django 5.0.6 on 2024-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallsettings',
            name='total_seats',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
